version: 2

jobs:
  lint:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update
      - run: apt install -y python3-pip
      - run: pip3 install -U black flake8
      - run: LC_ALL=C.UTF-8 black --check setup.py vandermonde/ test/*.py
      - run: flake8 setup.py vandermonde/ test/*.py
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip
      - run: pip3 install -U pytest pytest-cov
      - checkout
      # The actual test
      - run: pip3 install .
      - run: cd test/ && pytest --cov vandermonde
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
